### ISSUE TITLE
No news from this?

### ISSUE THREAD

**Issue by JonathanWi** [izifortune/angular-fluidbox#1]
Hey, was deeply interested in this, but I assumed the project is currently dead?

**Comment by izifortune** [comment]
Hi, i was working on something like this on my previous work. Didn't have much time to actually made it as a library. 

Anyway i christmas vacation is almost there, i may have some spare time to dedicate on this.

**Comment by JonathanWi** [comment]
Ah! Awesome then, I might start working on this too, I'll try to push some stuff here if I find the time during the week

**Comment by izifortune** [comment]
I think removing JQuery is too much right now, what do you think about it?

**Comment by JonathanWi** [comment]
I think it's unnecessary too, we should just wrap it like [angular slick](https://github.com/devmark/angular-slick-carousel) is doing! 
What do you think?

**Comment by izifortune** [comment]
Well ideally i would like to remove jquery from it ( still a huge dep especially on angularjs projects ) but i realise that at the moment it would require more time to do that.

Basic wrapper is done, just want to finalise it and add options to it. Later today gonna push it on the repo

**Comment by izifortune** [comment]
Basic wrapper is published, i also published on npm and bower. I added a couple of todos that will be nice to have, maybe later on i can tackle them.

**Comment by JonathanWi** [comment]
This is awesome news! I'm surprised that no one has ever developed a jquery-free version of this awesome plugin, especially since it's from medium. Do you think we should create a new repo for this purpose, and then move this plugin peer dependency from the jquery-based to ours? 

Anyway, thanks a lot for your work! 

—
