### ISSUE TITLE
Error: t.fluidbox is not a function

### ISSUE THREAD

**Issue by MateuszWilk** [izifortune/angular-fluidbox#3]
Hi, i'm getting this error when loading my template with angular-fluidbox directive:
`Error: t.fluidbox is not a functio.  (In 't.fluidbox(o)', 't.fluidbox' is undefined)`
Included 'fluidbox' in module declaration and added fluidbox directive attribute to my `<a>` tags.

**Comment by izifortune** [comment]
Hi, have you included this library as well? https://github.com/terrymun/Fluidbox mine is only a wrapper around that
